objects/Discount_Rule__mdt.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Segment__c</fullName>
        <label>Product Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Validity__c</fullName>
        <label>Product Validity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rule_Name__c</fullName>
        <label>Rule Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>category__c</fullName>
        <label>category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronics</fullName>
                    <default>true</default>
                    <label>Electronics</label>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount Rule</label>
    <pluralLabel>Discount Rules</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>category__c</fullName>
        <label>category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer_segment__c</fullName>
        <label>customer segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/custommetadatatestclass.cls
@istest
public class custommetadatatestclass {
   


     @isTest
    static void testApplyDiscount() {
       
       
        Discount_Rule__mdt rule = new Discount_Rule__mdt(  
            Rule_Name__c = Label.text1,
            Discount_Percentage__c =10,
            Product_Segment__c = Label.Product_segment,
            category__c = 'TestCategory',
            Product_Validity__c = System.today()
        ); 
        
        

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            Customer_Segment__c = 'TestSegment',
            category__c = 'TestCategory',
            CloseDate = Date.today(),
            StageName = 'Closed Won'
        );
        insert opp;
     
        System.runAs(new user(Id = UserInfo.getUserId())) {

        custommetadatanewclass.applyDiscount(opp.Category__c, opp.Customer_Segment__c);

        // Test applying discount
         // Test applying discount
        Test.startTest();
        Decimal discountPercentage = CustomMetadataNewClass.applyDiscount(opp.Customer_Segment__c, opp.Category__c);
        Test.stopTest();

        // Add assertions
     
    }
}
}